export const SET_USER = "SET_USER";
//EMPLOYEES
export const SET_EMPLOYEES = "SET_EMPLOYEES";//
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";//
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
//EMPLOYEE
export const SET_CURRENT_EMPLOYEE = "SET_CURRENT_EMPLOYEE";//
export const DELETE_CURRENT_EMPLOYEE = "DELETE_CURRENT_EMPLOYEE";//
//EMPLOYEES_ARCHIVE
export const SET_EMPLOYEES_ARCHIV = "SET_EMPLOYEES_ARCHIV";//
export const DELETE_EMPLOYEE_ARCHIV = "DELETE_EMPLOYEE_ARCHIV";//

//ROLES
export const SET_ROLES = "SET_ROLES";//
export const ADD_ROLE = "ADD_ROLE";//
export const EDIT_ROLE = "EDIT_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";
//ROLE
export const SET_CURRENT_ROLE = "SET_CURRENT_ROLE";//
export const DELETE_CURRENT_ROLE = "DELETE_CURRENT_ROLE";